#!/bin/bash

REALPATH=`perl -e 'use Cwd "abs_path";print abs_path(shift)' $0`
cd `dirname $REALPATH`

onedatastore update 0 bootstrapdummy/update.datastore0
onedatastore update 1 bootstrapdummy/update.datastore1

onehost create kvm_dummy -i dummy -v dummy -n dummy

onevnet create bootstrapdummy/create.vnet

touch /tmp/dummy_image_for_opennebula
oneimage create bootstrapdummy/create.image -d 1

onetemplate create bootstrapdummy/create.template

